### ISSUE TITLE
Remember me didn't work.

### ISSUE THREAD

**Issue by Jafee** [Jafee/demo#2]
@vpavic I have another question, the [issue](https://github.com/spring-projects/spring-session/issues/1112) has been closed, and I'm not sure to open one more. I configured the SecurityConfig class as described in the [document](https://docs.spring.io/spring-session/docs/2.0.5.BUILD-SNAPSHOT/reference/html5/#spring-security-rememberme).

    @Override
    protected void configure(HttpSecurity http) throws Exception {

        http
                // ... additional configuration ...
                .and()
                    .rememberMe()
                    .rememberMeServices(rememberMeServices())
               // ... additional configuration ...
    }

    @Bean
    RememberMeServices rememberMeServices() {
        SpringSessionRememberMeServices rememberMeServices = new SpringSessionRememberMeServices();
        rememberMeServices.setAlwaysRemember(true);
        return rememberMeServices;
    }

It didn't work. If I remove the spring session module, remember me will work.

I am very grateful for your help and forward to your reply.

**Comment by vpavic** [comment]
Looking at your sample app, it appears to be working correctly for me. Can you clarify what exactly do you mean by:

> It didn't work. If I remove the spring session module, remember me will work.

**Comment by Jafee** [comment]
Now this project(master branch), after logging in to the account, does not write a cookie for the browser.  Turn off your browser and you will need to log in again.

If you remove the spring session module, the browser will write a cookie named remember-me after logging in, and the project after removing the spring session module is [here](https://github.com/Jafee/demo/tree/no-spring-session).

My English is not very good, And thanks for your patience @vpavic .

**Comment by vpavic** [comment]
Your english is just fine @Jafee.

Spring Session backed remember me works just fine for me with this sample app. Note that `SpringSessionRememberMeServices` doesn't generate an additional cookie for remember me, but rather simply sets session's `maxInactiveInterval` to 30 days and sets appropriate flag to request so that the `DefaultCookieSerializer` can set extended max-age for the session cookie.

Here are the relevant parts of the code:

https://github.com/spring-projects/spring-session/blob/2e26c6e9d3e0ae2305c010bb5bcee7c6b9768768/spring-session-core/src/main/java/org/springframework/session/security/web/authentication/SpringSessionRememberMeServices.java#L83-L84

https://github.com/spring-projects/spring-session/blob/2e26c6e9d3e0ae2305c010bb5bcee7c6b9768768/spring-session-core/src/main/java/org/springframework/session/web/http/DefaultCookieSerializer.java#L117-L122

**Comment by Jafee** [comment]
@vpavic Understand, thank you for your clear explanation, and I have benefited from your communication.

In addition, if `SpringSessionRememberMeServices` can complement the cookie read and write operations in `loginSuccess`, `autoLogin` and `loginFail` like `PersistentTokenBasedRememberMeServices` and `TokenBasedRememberMeServices`, it will be used more in line with our expectations.

**Comment by vpavic** [comment]
NP @Jafee, glad I could help - it's always easier to provide support if users put together a sample app so thank you for that.

If you have any problems or improvement suggestions for `SpringSessionRememberMeServices` please open a ticket on Spring Session issues.
